services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: umbook_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./umbook-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/umbook_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires"
      DB_USER: root
      DB_PASS: root
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./umbook-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
